# Scenario:
# ---------
#
# You have application that creates new Entra ID application in a tenant.
# You have "Application.ReadWrite.OwnedBy" permission granted to your application.
# You want to give admin consent to newly created applications
# using permission: DelegatedPermissionGrant.ReadWrite.All

@tenant = {{$dotenv tenant}}
@clientID = {{$dotenv clientID}}
@clientSecret = {{$dotenv clientSecret}}

### Get token
# @name tokenResponse
POST https://login.microsoftonline.com/{{tenant}}/oauth2/v2.0/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id={{clientID}}
&client_secret={{clientSecret}}
&scope=https://graph.microsoft.com/.default
&grant_type=client_credentials

# Response:
# {
#   "token_type": "Bearer",
#   "expires_in": 3599,
#   "ext_expires_in": 3599,
#   "access_token": "eyJ...xwQ"
# }

### Find all owned applications
# @name ownedApplications
GET https://graph.microsoft.com/v1.0/servicePrincipals(appId='{{clientID}}')/ownedObjects HTTP/1.1
Content-type: application/json
Authorization: Bearer {{tokenResponse.response.body.access_token}}

### Create application in the tenant
# @name application
POST https://graph.microsoft.com/v1.0/applications HTTP/1.1
Content-type: application/json
Authorization: Bearer {{tokenResponse.response.body.access_token}}

{
  "displayName": "App Created 1"
}

### Get application owner of one specific application
# @name applicationOwner
GET https://graph.microsoft.com/v1.0/applications/{{application.response.body.id}}/owners HTTP/1.1
Content-type: application/json
Authorization: Bearer {{tokenResponse.response.body.access_token}}

### Create service principal to the tenant
# @name servicePrincipal
POST https://graph.microsoft.com/v1.0/servicePrincipals HTTP/1.1
Content-type: application/json
Authorization: Bearer {{tokenResponse.response.body.access_token}}

{
  "appId": "{{application.response.body.appId}}"
}

# Response:
# {
#   "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#servicePrincipals/$entity",
#   "id": "deb13040-a70a-42fa-ab76-afba7fe32caa",
# ...
#   "appId": "b99b48ff-db35-4958-8dbe-0e8acd56d401",
#   "applicationTemplateId": null,
#   "appOwnerOrganizationId": "f13b9d7d-da00-465f-b05a-0e8768b5bb1f",
#   "servicePrincipalType": "Application",
#   "signInAudience": "AzureADMyOrg",
# ...
# }

### Fetch service principal
# @name servicePrincipalResponse
GET https://graph.microsoft.com/v1.0/servicePrincipals?$filter=id eq '{{servicePrincipal.response.body.id}}'&$select=id,displayName,appId,oauth2PermissionScopes HTTP/1.1
Content-type: application/json
Authorization: Bearer {{tokenResponse.response.body.access_token}}

### Fetch Microsoft Graph service principal to get resource id
# @name servicePrincipalResponseGraph
GET https://graph.microsoft.com/v1.0/servicePrincipals?$filter=displayName eq 'Microsoft Graph'&$select=id,displayName,appId,oauth2PermissionScopes HTTP/1.1
Content-type: application/json
Authorization: Bearer {{tokenResponse.response.body.access_token}}

### Grant consent
# @name consentResponse
POST https://graph.microsoft.com/v1.0/oauth2PermissionGrants HTTP/1.1
Authorization: Bearer {{tokenResponse.response.body.access_token}}
Content-type: application/json

{
   "clientId": "{{servicePrincipal.response.body.id}}",
   "consentType": "AllPrincipals",
   "resourceId": "{{servicePrincipalResponseGraph.response.body.value[0].id}}",
   "scope": "offline_access User.Read email profile openid"
}

# Response (A) without "DelegatedPermissionGrant.ReadWrite.All" permission:
# {
#   "error": {
#     "code": "Authorization_RequestDenied",
#     "message": "Insufficient privileges to complete the operation.",
#     "innerError": {
#       "date": "2025-10-20T12:32:52",
#       "request-id": "0eb1b..ad2",
#       "client-request-id": "0eb...ad2"
#     }
#   }
# }

# Response (B) with "DelegatedPermissionGrant.ReadWrite.All" permission:
# {
#   "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#oauth2PermissionGrants/$entity",
#   "clientId": "156...4f8",
#   "consentType": "AllPrincipals",
#   "id": "n7Fp...YNk",
#   "principalId": null,
#   "resourceId": "615...60d9",
#   "scope": "offline_access User.Read email profile openid"
# }

### Fetch a "random" service principal
# @name servicePrincipalResponseRandom
GET https://graph.microsoft.com/v1.0/servicePrincipals?$filter=displayName eq 'Random' HTTP/1.1
Content-type: application/json
Authorization: Bearer {{tokenResponse.response.body.access_token}}

### Grant consent
# @name consentResponseRandom
POST https://graph.microsoft.com/v1.0/oauth2PermissionGrants HTTP/1.1
Authorization: Bearer {{tokenResponse.response.body.access_token}}
Content-type: application/json

{
   "clientId": "{{servicePrincipalResponseRandom.response.body.value[0].id}}",
   "consentType": "AllPrincipals",
   "resourceId": "{{servicePrincipalResponseGraph.response.body.value[0].id}}",
   "scope": "offline_access User.Read email profile openid"
}

# Response:
# {
#   "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#oauth2PermissionGrants/$entity",
#   "clientId": "30...05e",
#   "consentType": "AllPrincipals",
#   "id": "m94...dYNk",
#   "principalId": null,
#   "resourceId": "615...60d9",
#   "scope": "offline_access User.Read email profile openid"
# }
