# Instructions:
# - See API Reference (and especially required permissions): 
# https://docs.microsoft.com/en-us/graph/api/application-post-applications?view=graph-rest-1.0&tabs=http
#
# - See other examples from Postman collection (and especially how to get token)
# https://github.com/microsoftgraph/microsoftgraph-postman-collections
#
# - Alternative: Get access token using Azure CLI
# az account get-access-token --resource https://graph.microsoft.com/ --query accessToken -o tsv | clip
#
# - Study your tokens permissions:
# https://jwt.ms/
#
# - You should have following permissions (from above API reference page):
#   Permission type  Permissions (from least to most privileged)
#   Delegated        Directory.AccessAsUser.All
#   Application      Application.ReadWrite.OwnedBy, Application.ReadWrite.All
#
@endpoint = https://graph.microsoft.com/beta

@accessToken = {{$dotenv accessToken}}

### Create application
# @name application
POST {{endpoint}}/applications HTTP/1.1
Content-type: application/json
Authorization: Bearer {{accessToken}}

{
  "displayName": "AAD App Scenario",
  "signInAudience": "AzureADMyOrg",
  "requiredResourceAccess": [
    {
      "resourceAppId": "00000003-0000-0000-c000-000000000000",
      "resourceAccess": [
        {
          "id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
          "type": "Scope"
        }
      ]
    },
  ],
  "web": {
    "implicitGrantSettings": {
      "enableIdTokenIssuance": true
    },
    "redirectUris": [
      "https://<yourapphere>.azurewebsites.net/.auth/login/aad/callback"
    ]
  }
}

### Fetch application by id
# @name app
@applicationObjectId = {{application.response.body.id}}
GET {{endpoint}}/applications/{{applicationObjectId}} HTTP/1.1
Content-type: application/json
Authorization: Bearer {{accessToken}}

### Delete application by id
DELETE {{endpoint}}/applications/{{applicationObjectId}} HTTP/1.1
Content-type: application/json
Authorization: Bearer {{accessToken}}
