# Instructions:
# - Get access token using Azure CLI as yourself (dev scenarios)
# az account get-access-token --resource https://management.azure.com
#
# - Get access token using Azure CLI as Service Principal
# az login --service-principal --username APP_ID --password PASSWORD --tenant TENANT_ID
# az account get-access-token --resource https://management.azure.com
#
# https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/apis/list-by-service
## 
##
@endpoint = https://management.azure.com
@apiVersion = 2019-12-01

@subscription = guid
@resourceGroupName = name
@serviceName = name

@accessToken = token

### List APIs
GET {{endpoint}}/subscriptions/{{subscription}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.ApiManagement/service/{{serviceName}}/apis
    ?api-version={{apiVersion}}
Authorization: Bearer {{accessToken}}
Content-type: application/json

### Import Petstore Swagger
# @name importResponse
PUT {{endpoint}}/subscriptions/{{subscription}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.ApiManagement/service/{{serviceName}}/apis/petstore
    ?api-version={{apiVersion}}
Authorization: Bearer {{accessToken}}
Content-type: application/json

{
  "properties": {
    "format": "swagger-link-json",
    "value": "http://petstore.swagger.io/v2/swagger.json",
    "path": "petstore"
  }
}

# Note: If you start multiple import you might get this error:
# HTTP/1.1 409 Conflict

# {
#   "error": {
#     "code": "PessimisticConcurrencyConflict",
#     "message": "Operation on the API is in progress",
#     "details": null
#   }
# }

### Get import output
@location = {{importResponse.response.headers.location}}
GET {{location}}
Authorization: Bearer {{accessToken}}
Content-type: application/json

### Get Petstore API
GET {{endpoint}}/subscriptions/{{subscription}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.ApiManagement/service/{{serviceName}}/apis/petstore
    ?api-version={{apiVersion}}
Authorization: Bearer {{accessToken}}
Content-type: application/json

### Get API Operation Policy
@api = yourapi
@apiOperation = yourapioperation
GET {{endpoint}}/subscriptions/{{subscription}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.ApiManagement/service/{{serviceName}}/apis/{{api}}/operations/{{apiOperation}}/policies/policy
    ?api-version={{apiVersion}}
Authorization: Bearer {{accessToken}}
Content-type: application/json
