# Instructions:
# - Get access token using Azure CLI as yourself (dev scenarios)
# az account get-access-token --resource https://management.azure.com
#
# - Get access token using Azure CLI as Service Principal
# az login --service-principal --username APP_ID --password PASSWORD --tenant TENANT_ID
# az account get-access-token --resource https://management.azure.com
#
# Metrics list:
# https://docs.microsoft.com/en-us/rest/api/monitor/metrics/list
#
# Supported metrics with Azure Monitor:
# https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported
##
@endpoint = https://management.azure.com
@apiVersion = 2018-01-01

@subscription = guid
@resourceGroupName = name
@logicAppName = name

@accessToken = token

### Query: ActionsCompleted metric
@metricnames = ActionsCompleted
@timespan = 2020-08-27T00:00:00Z/2020-08-28T00:00:00Z
@aggregation = sum
GET {{endpoint}}/subscriptions/{{subscription}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.Logic/workflows/{{logicAppName}}/providers/microsoft.insights/metrics
    ?api-version={{apiVersion}}
    &metricnames={{metricnames}}
    &timespan={{timespan}} HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-type: application/json
