# Instructions:
# - Get access token (dev scenarios)
# az account get-access-token --resource https://management.azure.com
# (Get-AzAccessToken -ResourceUrl https://management.azure.com).Token | clip
#
# - Get access token using Azure CLI as Service Principal
# az login --service-principal --username APP_ID --password PASSWORD --tenant TENANT_ID
# az account get-access-token --resource https://management.azure.com
#
# Link:
# https://docs.microsoft.com/en-us/rest/api/resources/resources/list
## 
##
@endpoint = https://management.azure.com
@apiVersion = 2021-04-01

@subscription = {{$dotenv subscription}}

@filter = resourceType eq 'Microsoft.Web/sites'
@expand = createdTime,changedTime,provisioningState
@accessToken = {{$dotenv accessToken}}

### Get resources
GET {{endpoint}}/subscriptions/{{subscription}}/resources?api-version={{apiVersion}}&$filter={{filter}}&$expand={{expand}}
Authorization: Bearer {{accessToken}}
Content-type: application/json


### Get resources
GET {{endpoint}}/subscriptions/{{subscription}}/resources?api-version={{apiVersion}}
Authorization: Bearer {{accessToken}}
Content-type: application/json
